# Generated by Django 5.0.3 on 2024-03-11 16:03

import datetime
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Jproduct',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Product Name')),
                ('price', models.IntegerField()),
                ('cat', models.IntegerField(choices=[(1, 'Braslets'), (2, 'Rings'), (3, 'Earrings')], verbose_name='Category')),
                ('product_details', models.CharField(max_length=500, verbose_name='Product Details')),
                ('is_active', models.BooleanField(default=True, verbose_name='Available')),
                ('p_img', models.ImageField(upload_to='uploads/')),
            ],
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('orderid', models.CharField(max_length=50)),
                ('trackingid', models.CharField(blank=True, max_length=50, null=True)),
                ('address', models.CharField(max_length=80)),
                ('paymentlink', models.CharField(blank=True, max_length=50, null=True)),
                ('paymentstatus', models.CharField(blank=True, max_length=50, null=True)),
                ('amt', models.IntegerField(default=0)),
                ('userid', models.ForeignKey(db_column='userid', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='UserCart',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField(default=1)),
                ('total', models.IntegerField(default=0)),
                ('is_ordered', models.BooleanField(default=False)),
                ('order_date', models.DateTimeField(default=datetime.datetime.now)),
                ('order', models.ForeignKey(blank=True, db_column='orderid', null=True, on_delete=django.db.models.deletion.CASCADE, to='jwelleryapp.order')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='jwelleryapp.jproduct', verbose_name='Product')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
