# Generated by Django 5.0.3 on 2024-03-11 16:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('jwelleryapp', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usercart',
            name='order_date',
        ),
    ]
