# Generated by Django 5.0.3 on 2024-03-15 17:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('jwelleryapp', '0005_address'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='paymentlink',
        ),
        migrations.RemoveField(
            model_name='order',
            name='trackingid',
        ),
    ]
